### ISSUE TITLE
[Feature Request] Nested Repeaters

### ISSUE THREAD

**Issue by patrickpalfinger** [nk-crew/lazy-blocks#314] opened 2024-05-23 06:21 UTC
### Issue description:
Nested repeaters would be a really useful feature, right now I am creating blocks with only a single "Inner Block" field, in which I am putting multiple Blocks which include a repeater field. I've seen it would be possible with ACF.

**Comment by nk-o** [comment] 2024-05-23 11:57
This is a duplicate of https://github.com/nk-crew/lazy-blocks/issues/89. There is currently no solution, but one may be available in the future.

**Closed by nk-o** 2024-05-23 11:57 UTC
