### ISSUE TITLE
Error log overflowing

### ISSUE THREAD

**Issue by rdssteenis** [nk-crew/lazy-blocks#333] opened 2024-12-05 09:33 UTC
### Issue Description
The plugin **Lazy Blocks** is generating an excessive number of PHP notices in my WordPress error log, causing it to grow rapidly. The notices appear to be related to translation loading being triggered too early:

`PHP Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the lazy-blocks domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in /public_html/wp-includes/functions.php on line 6114`

### PHP Version
PHP 8.2

### Lazy Blocks Version
Version 3.7.0 (pro)

### WordPress Version
6.7.1

**Comment by nk-o** [comment] 2024-12-05 09:40
Duplicate of https://github.com/nk-crew/lazy-blocks/issues/325. Already fixed in the dev build, soon will be available in the release.

**Closed by nk-o** 2024-12-05 09:40 UTC

**Comment by rdssteenis** [comment] 2024-12-05 09:43
Awesome! Thank you 👍
