### ISSUE TITLE
Bug report: Lazyblocks does not update meta fields on publish / update.

### ISSUE THREAD

**Issue by jaapie1989** [nk-crew/lazy-blocks#137] opened 2020-04-20 10:46 UTC
Dear Developer,

Love this plugin, however i just run into the following issue. It seems like whenever  _'save in meta'_ field is checked. The LZB controller won't update the meta field whenever you save or. update a post or page. 

I currently have a block which should be saved in the meta field, however every time i try to save or update an post, the meta fields won't be updated. When i refresh the page after i saved my post the old input value is showed again. 

Can this issue be resolver? Thank you in advance.

**Comment by nk-o** [comment] 2020-04-28 20:45
Please, provide detailed info on how to reproduce the problem. On my test server meta values saved with no problem.

**Comment by jaapie1989** [comment] 2020-04-29 08:36
The meta values are saved indeed. But once you edit a post or page and try to change a value and overwrite them, this does not work. It does not work with the standard Wordpress theme and plugin out of the box.

**Comment by nk-o** [comment] 2020-04-29 08:47
It is working as well.

**Comment by NielsWPN** [comment] 2020-09-18 16:03
Hi

I came here after looking to solve a similar problem: the field default value was not displayed correctly (displayed 0) when 'saved in meta' was ticked.

Custom fields panel was the problem — I think this info should be in the documentation as I thought blocks with meta and WP custom fields could work together (one updating the other and vice versa).

Best

**Comment by cheggy** [comment] 2020-11-11 08:29
I had the issue of not being able to save items that were saving to meta data.  
I would edit the input and it would pop up the toast to say it had saved but looking at the published page, the change was not made and reloading the edit page would show the old content.
Upon looking in the console, there are a bunch of warnings about duplicate IDs.  Which was related to having the Custom Fields panel displayed (I guess same ID for the inputs)

From the block edit screen, go to the 'dot dot dot' more menu in the top right, select options and unselect 'custom fields'.  Then save and reload.  This solved it for me.

**Comment by nk-o** [comment] 2021-08-17 18:54
I will close this since the problem is because of the Gutenberg feature.

**Closed by nk-o** 2021-08-17 18:54 UTC
Labels: question
