### ISSUE TITLE
[Bug] Creating a block doesn't save the data, ending in an Exception

### ISSUE THREAD

**Issue by dievardump** [nk-crew/lazy-blocks#198] opened 2021-04-04 21:32 UTC
### Issue description:

Every time I create a block, save it and publish it, the content is not saved, only the block creation.

This stops Wordpress from working because an exception is then launched at any page load because the plugin tries to register a block with the slug "lazyblocks/" 

If I comment in `plugins/lazy-blocks/classes/class-blocks.php` the line 1216 `register_block_type( $block['slug'], $data );` and go back to the admin I can edit the block and then saving works well.

### Lazy Blocks Version:

Version 2.3.1 

### WordPress Version:

WordPress 5.7

### Any helpful information to reproduce the issue (screenshots, code parts)

Using Firefox. I just did the installation of the plugin through the plugin manager.

Image of the thrown exception: 

https://imgur.com/a/gJ4qbFo

**Comment by nk-o** [comment] 2021-04-11 16:34
duplicate of https://github.com/nk-crew/lazy-blocks/issues/188

**Closed by nk-o** 2021-04-11 16:34 UTC
