### ISSUE TITLE
Gutenberg edits all blocks at the same time

### ISSUE THREAD

**Issue by fly-oinotna** [nk-crew/lazy-blocks#224] opened 2021-10-25 08:47 UTC
### Issue description:
We generate accordions using a simple lazy block loop. Works great until one block per page is used.
If we generate multiple accordion blocks in the same page, all blocks content will be edited at the same time.

### Lazy Blocks Version:
2.4.3

### WordPress Version:
5.8.1

### Any helpful information to reproduce the issue (screenshots, code parts)
![Schermata 2021-10-25 alle 10 45 10](https://user-images.githubusercontent.com/19783808/138664163-dff0d92a-a5c9-4641-ae9e-185b10a80303.png)

**Comment by nk-o** [comment] 2021-11-04 18:11
Unfortunately, I can't reproduce this issue. If you can provide a step-by-step guide on how to create this block (from scratch) and how to insert it in the post to reproduce this bug, I will be able to fix it.

**Comment by predaytor** [comment] 2021-11-26 19:58
I think that happens when using field type Classic Editor (WYSIWYG ).

**Comment by gmesnard** [comment] 2022-02-16 09:21
+1, I have the same problem.
Three blocks in a page, when I edit a block, all 3 are modified identically.

**Comment by mem-shimoyama-takumi** [comment] 2022-07-21 00:48
I don't know if this is the same problem, but when there are two or more Classic Editor (WYSIWYG ), pressing Ctrl+A selects the contents of all WYSIWYGs except the one that is selected, and then the contents of all WYSIWYGs are the same.
Translated by DeepL

**Comment by nk-o** [comment] 2024-10-10 16:08
Closing as I cannot reproduce the issue.

**Closed by nk-o** 2024-10-10 16:08 UTC
Labels: question
